services:
  django:
    build:
      context: .
      dockerfile: Docker/Django/Dockerfile
    container_name: django
    restart: unless-stopped
    volumes:
      - .:/app
      - ./app/db.sqlite3:/app/app/db.sqlite3
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000


networks:
  django_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24

