services:
  django:
    build:
      context: .
      dockerfile: Docker/Django/Dockerfile
    container_name: django
  # command entfernt, da jetzt im Dockerfile geregelt

    volumes:
      - .:/app

    ports:
      - "8000:8000"
    
    #depends_on:
    #  - db

    networks:
      - django_network


networks:
  django_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
