# Generated by Django 4.2.28 on 2026-02-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperium', '0003_add_m_color_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cls_imperium',
            name='m_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='cls_rassen',
            name='m_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        # unique=True für m_color hinzufügen
        migrations.AlterField(
            model_name='cls_imperium',
            name='m_color',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
