# Generated by Django 4.2.28 on 2026-02-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imperium', '0004_add_unique_to_m_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cls_imperium',
            name='m_color',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
